service: bookspace-aligo-server

plugins:
  - "serverless-plugin-typescript"
  - serverless-tscpaths
  - serverless-offline

useDotenv: true

custom:
  tscpaths:
    buildPath: .build
    tsconfigPath: tsconfig.json
  STAGE: ${self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: ${opt:stage, 'alpha'}
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  environment:
    STAGE: ${self:provider.stage}
    DB_PORT: ${ssm:/${self:custom.STAGE}-db-port~true}
    DB_HOST: ${ssm:/${self:custom.STAGE}-db-host~true}
    DB_USERNAME: ${ssm:/${self:custom.STAGE}-db-username~true}
    DB_NAME: ${ssm:/${self:custom.STAGE}-auth-db-name~true}
    DB_PASSWORD: ${ssm:/${self:custom.STAGE}-db-password~true}
    JWT_SECRET: ${ssm:/jwtSecret~true}
    PBKDF2_SALT: ${ssm:/pbkdf2Salt~true}
    IMP_KEY: ${ssm:/impKey~true}
    IMP_SECRET: ${ssm:/impSecret~true}
    ALIGO_API_KEY: ${ssm:/aligo-api-key~true}
    REDIS_HOST: ${ssm:/redis-host~true}
    REDIS_PORT: ${ssm:/redis-port~true}
    KAKAO_REST_API_KEY: ${ssm:/kakao-rest-api-key~true}
    KAKAO_CLIENT_SECRET: ${ssm:/kakao-client-secret~true}

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
